image: pikalab/ci:jdk-gradle-git-graphviz

variables:
  ORG_GRADLE_PROJECT_orchidBaseUrl: "https://pika-lab.gitlab.io/tuprolog/2p-in-kotlin/"

cache:
  paths:
    - $HOME/.gradle/
    - $HOME/.m2/
    - gradle/
    - .gradle/
    - build/
    - '**/build/'
    - core/src/commonMain/kotlin/it/unibo/tuprolog/Info.kt

stages:
  - check
  - build
  - test

Check Code Style:
  stage: check
  script:
    - gradle clean
    - gradle ktlintCheck --parallel
  artifacts:
    paths:
      - "**/build/reports/ktlint/"
  only:
    - branches

Compile JVM:
  stage: build
  script:
    - gradle jvmMainClasses jvmTestClasses --parallel
  only:
    - branches

Compile JS:
  stage: build
  script:
    - gradle jsMainClasses jsTestClasses --parallel
  only:
    - branches

Test JVM:
  stage: test
  script:
    - gradle jvmTest
  artifacts:
    reports:
      junit: "**/build/test-results/jvmTest/*.xml"
  only:
    - branches

Test JS:
  stage: test
  script:
    - gradle jsTest
  only:
    - branches

pages:
  script:
    - mkdir public
    - gradle orchidBuild
    - cp -r documentation/build/docs/orchid/* public
  artifacts:
    paths:
      - public
  allow_failure: true
  only:
    - /^(master)|(release)|(documentation)$/
