image: pikalab/ci:jdk12oracle-gradle6-git

variables:
  GOPTS: "--no-daemon --console=plain"

before_script:
  - chmod +x gradlew

cache:
  paths:
    - /root/.gradle/
    - gradle/
    - build/
    - .gradle/

build:
  stage: build
  script: gradle assemble $GOPTS

test:
  stage: test
  script: gradle check $GOPTS

publish-bintray:
  stage: deploy
  script: gradle publishAllToBintray
  environment:
    name: Bintray
    url: "https://bintray.com/pika-lab/tuprolog"
  when: manual
