image: pikalab/ci:jdk13oracle-git-graphviz

variables:
  GOPTS: "--no-daemon --console=plain"
  CI: "true"
  BEFORE_TASK: ""
  AFTER_TASK: ""
  GCMD: "./gradlew"
  BUILD_TASK: "assemble"
  TEST_TASK: "check -x dokka"
  TEST_JVM_TASK: "jvmTest -x dokka"
  TEST_JS_TASK: "clean jsTest -x dokka"
  BINTRAY_TASK: "publishAllToBintray"
  NPM_TASK: "clean jsMain npmPublish"
  PAGES_TASK: "orchidBuild"
  ORG_GRADLE_PROJECT_orchidBaseUrl: "https://pika-lab.gitlab.io/tuprolog/2p-in-kotlin/"

before_script:
  - chmod +x gradlew

#cache:
#  paths:
#    - /root/.gradle/caches
#    - /root/.gradle/daemon
#    - /root/.gradle/wrapper
#    - gradle/
#    - build/
#    - .gradle/

Compile:
  stage: build
  script: $GCMD $BEFORE_TASK $BUILD_TASK $AFTER_TASK $GOPTS

Test JVM:
  stage: test
  script: $GCMD $BEFORE_TASK $TEST_JVM_TASK $AFTER_TASK $GOPTS

Test JS:
  stage: test
  script: $GCMD $BEFORE_TASK $TEST_JS_TASK $AFTER_TASK $GOPTS
  allow_failure: true

Deploy to Bintray:
  stage: deploy
  script: $GCMD $BEFORE_TASK $BINTRAY_TASK $AFTER_TASK $GOPTS
  environment:
    name: Bintray
    url: "https://bintray.com/pika-lab/tuprolog"
  only:
    - /^(master)|(release)|(develop)$/

Deploy to NPM:
  stage: deploy
  script: $GCMD $BEFORE_TASK $NPM_TASK $AFTER_TASK $GOPTS
  environment:
    name: NPM
    url: "https://www.npmjs.com/org/tuprolog"
  only:
    - /^(master)|(release)|(develop)$/

pages:
  script:
    - mkdir public
    - $GCMD $BEFORE_TASK $PAGES_TASK $AFTER_TASK $GOPTS
    - cp -r documentation/build/docs/orchid/* public
  artifacts:
    paths:
      - public
  allow_failure: true
  only:
    - /^(master)|(release)|(documentation)$/
