image: pikalab/ci:jdk13oracle-git

variables:
  GOPTS: "--no-daemon --console=plain --stacktrace"
  CI: "true"
  BEFORE_TASK: ""
  AFTER_TASK: ""
  GCMD: "./gradlew"
  BUILD_TASK: "assemble"
  TEST_TASK: "check -x dokka"
  TEST_JVM_TASK: "jvmTest -x dokka"
  TEST_JS_TASK: "clean jsTest -x dokka"
  BINTRAY_TASK: "publishAllToBintray"
  PAGES_TASK: "orchidBuild"
  ORG_GRADLE_PROJECT_orchidBaseUrl: "https://pika-lab.gitlab.io/tuprolog/2p-in-kotlin/"

before_script:
  - chmod +x gradlew

# cache:
#   paths:
#     - /root/.gradle/
#     - gradle/
#     - build/
#     - .gradle/

Compile:
  stage: build
  script: $GCMD $BEFORE_TASK $BUILD_TASK $AFTER_TASK $GOPTS

Test JVM:
  stage: test
  script: $GCMD $BEFORE_TASK $TEST_JVM_TASK $AFTER_TASK $GOPTS

Test JS:
  stage: test
  script: $GCMD $BEFORE_TASK $TEST_JS_TASK $AFTER_TASK $GOPTS

Publish to Bintray (dev):
  stage: deploy
  script: $GCMD $BEFORE_TASK $BINTRAY_TASK $AFTER_TASK $GOPTS
  environment:
    name: Bintray
    url: "https://bintray.com/pika-lab/tuprolog"
  only:
    - /^develop$/

Publish Releases to Bintray:
  stage: deploy
  script: $GCMD $BEFORE_TASK $BINTRAY_TASK $AFTER_TASK $GOPTS
  environment:
    name: Bintray
    url: "https://bintray.com/pika-lab/tuprolog"
  only:
    - /^(master)|(release)$/

pages:
  script:
    - mkdir public
    - $GCMD $BEFORE_TASK $PAGES_TASK $AFTER_TASK $GOPTS
    - cp -r documentation/build/docs/orchid/* public
  artifacts:
    paths:
      - public
  only:
    - feature/doc
