name: ci
on:
  push:
    branches:
      - master
      - develop
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - &cache_jdk
        name: Cache JDK
        uses: actions/cache@v2
        env:
          jdk-version: &jdk_version
            openjdk@~1.15.0
        with:
          path: $HOME/.jabba
          key: ${{ runner.os }}-jdk-${{ env.jdk-version }}
          restore-keys: |
            ${{ runner.os }}-jdk-
            ${{ runner.os }}-

      - &install_jdk
        uses: battila7/jdk-via-jabba@v1
        with:
          jdk: *jdk_version

      - name: Show Env
        run: gradle --version

  build:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - &checkout_code
        name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history

      - &setup_env
        name: Set up Environment
        uses: allenevans/set-env@v1.0.0
        with:
          PROJECT_NAME: 2P-Kt
          GOPTS: "--no-daemon --console=plain"

      - *cache_jdk

      - *install_jdk

      - &cache_gradle
        name: Cache Gradle Data
        uses: actions/cache@v2
        env:
          jdk-version: *jdk_version
        with:
          path: |
            $HOME/.m2
            $HOME/.gradle/caches
            $HOME/gradle/wrapper
            **/build
            **/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Setup Gradle
        run: gradle $GOPTS

      - name: Check Code Style
        run: gradle $OPTS ktlintCheck --parallel

      - name: Archive KtLint Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ktlint-reports
          path: '**/build/reports/ktlint'

      - name: Compile
        run: gradle $OPTS assemble --parallel

      - name: Test JVM
        run: gradle $OPTS jvmTest

      - name: Archive JVM Test Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: jvm-test-reports
          path: '**/build/reports/tests/jvmTest'

      - name: Test JS
        run: gradle $OPTS jsTest

      - name: Archive JS Test Reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: js-test-reports
          path: '**/build/reports/tests/jsTest'

      - name: Generate Doc
        run: gradle $OPTS dokkaHtml --parallel

      - name: Generate Molti-Module Doc
        run: gradle $OPTS dokkaHtmlMultiModule --parallel

      - name: Archive Doc
        uses: actions/upload-artifact@v2
        with:
          name: api-references
          path: build/dokka/htmlMultiModule

  deploy-maven-github:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - *checkout_code
      - *setup_env
      - *cache_jdk
      - *install_jdk
      - *cache_gradle

      - name: Sign Archives
        run: gradle $OPTS signAllPublications --parallel

      - name: Publish on GitHub Maven Repo
        run: gradle $OPTS publishAllPublicationsToMavenRepository --parallel
        env:
          ORG_GRADLE_PROJECT_sonatypeUrl: https://maven.pkg.github.com/tuProlog
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.GITHUB_TOKEN }}
