name: quick-check
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history

      - name: Set up Environment
        uses: allenevans/set-env@v1.0.0
        with:
          PROJECT_NAME: 2P-Kt
          GOPTS: "--no-daemon --console=plain"
          
#      - name: Install Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: 15.0.1 # The JDK version to make available on the path.
#          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
#          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: battila7/jdk-via-jabba@v1
        with:
          jdk: jabba install openjdk@1.15.0-1

#      - name: Ensure Gradle Wrapper is Executable
#        run: chmod +x gradlew

      - name: Setup Gradle
        run: gradle $GOPTS

      - name: Show Env
        run: gradle --version

      - name: Check Code Style
        run: gradle $OPTS ktlintCheck --parallel

      - name: Archive KtLint Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ktlint-reports
          path: '**/build/reports/ktlint'

      - name: Compile
        run: gradle $OPTS assemble --parallel

      - name: Test JVM
        run: gradle $OPTS jvmTest

      - name: Archive JVM Test Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: jvm-test-reports
          path: '**/build/reports/tests/jvmTest'

      - name: Test JS
        run: gradle $OPTS jsTest

      - name: Archive JS Test Reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: js-test-reports
          path: '**/build/reports/tests/jsTest'

      - name: Generate Doc
        run: gradle $OPTS dokkaHtml --parallel

      - name: Archive Doc
        uses: actions/upload-artifact@v2
        with:
          name: api-references
          path: build/dokka/htmlMultiModule
